version: '2'
volumes:
  data: {}
services:
  proxy:
    build: ./webserver
    depends_on:
      - data
    ports:
      - "80:80"
    volumes:
    - data:/usr/share/nginx/html/:r
  data:
    build: ./sensors
    expose:
      - "8080"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    volumes:
    - data:/data:rw