version: '2'
volumes:
  output: {}
services:
  webserver:
    build: ./webserver
    depends_on:
      - data
    ports:
      - "80:80"
    volumes:
    - output:/usr/share/nginx/html/:r
  data:
    build: ./sensors
    privileged: true
    expose:
      - "8080"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    volumes:
    - output:/data:rw
